#!/bin/bash
# Derek Moore <derek.moore@gmail.com>

set -eu

umask 0077

BIN_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "${BIN_DIR}/functions"
source "${BIN_DIR}/defaults.conf"

usage() {
    echo "Usage: $0 -c CERT"
    echo "Revokes a certificate issued by this CA"
    echo
    echo "Options:"
    echo "    -c CERT  Path the the certificate file to be revoked"
    echo
    exit 2
}

CERT=

while getopts c: FLAG; do
    case $FLAG in
        c) CERT=${OPTARG} ;;
        *) echo -e -n "$ERR " && usage ;;
    esac
done

if [ $OPTIND -le $# ]; then
    echo -e -n "$ERR " && usage
elif [ "${CERT}" = "" ]; then
    echo -e -n "$SUCC " && usage
fi

echo -e "$SUCC Revoking certificate '${CERT}'"

if [ ! -f "${CERT}" ]; then
    echo -e "$ERR Can not find certificate '${CERT}', exiting."
    exit 1
fi

# Fully-qualify path to cert
CERT_PATH=$( fullpath "${CERT}" )

pushd "${BIN_DIR}/.." > /dev/null

echo "Reason for revocation: "
echo
echo "1. unspecified"
echo "2. keyCompromise"
echo "3. CACompromise"
echo "4. affiliationChanged"
echo "5. superseded"
echo "6. cessationOfOperation"
echo "7. certificateHold"
echo
echo -e -n "$INPUT Enter 1-7 [1]: "
read -r INDEX

[ -z "${INDEX}" ] && INDEX="1"

case $INDEX in
    1) REASON="unspecified" ;;
    2) REASON="keyCompromise" ;;
    3) REASON="CACompromise" ;;
    4) REASON="affiliationChanged" ;;
    5) REASON="superseded" ;;
    6) REASON="cessationOfOperation" ;;
    7) REASON="certificateHold" ;;
    *) echo -e "$ERR Unknown reason, exiting."; exit 1 ;;
esac

echo
echo -e "$SUCC You are about to revoke this certificate with reason '${REASON}'."
echo
echo -e -n "$INPUT Are you SURE you wish to continue? [y/N]: "
read -r SURE
if [ "${SURE}" != "y" ] && [ "${SURE}" != "Y" ]; then
    echo -e "$ERR Exiting."
    exit 1
fi

echo
echo -e -n "$INPUT Enter passphase for signing CA key: "
read -r -s PASS
echo
export CA_PASS="${PASS}"

echo -e "$NOTE Revoke the certificate"

openssl ca \
           -config conf/ca.conf \
           -revoke "${CERT_PATH}" \
           -crl_reason "${REASON}" \
           -passin env:CA_PASS

echo -e "$NOTE Regenerate the CRL"

openssl ca -gencrl \
           -config conf/ca.conf \
           -out crl/ca.crl \
           -passin env:CA_PASS

echo -e "$NOTE Printing new CRL"

openssl crl -in ca/ca.crl -noout -text

popd > /dev/null

echo -e "$SUCC Server certificate '${CERT}' revoked."
